baseURL = "https://smartmachine.io"
languageCode = "en-us"
title = "SmartMachine"
theme = "ananke"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "params dot description"
  facebook = ""
  twitter = "https://twitter.com/chaossink"
  instagram = ""
  youtube = ""
  github = "https://github.com/smartmachine"
  gitlab = ""
  linkedin = "https://linkedin.com/in/knutster"
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-near-black"
  featured_image = "/images/banner.jpg"
  recent_posts_number = 2
